@startuml
class Member {
  -String name
}

class Home {
  +getProvideRoomInfos(): List<Room>
  +getAvailableRoomOnDate(DateRange): List<Accommodation>
  +reserve(Member, DateRange, Accommodation): void
}

class Room {
  +showRoomInfos(): List<Room>
  +calculateRoomPayment(DateRange): int
}

class Accommodation {
  -Room room
  +showSpecificDateAccommodations(DateRange): List<Accommodation>
  +confirmReservation(Accommodation): boolean
  -pendingReservation(): void
  +getPaymentAmount(DateRange): int
}

class Reservation {
  -Member member
  -DateRange reservationDate
  -Accommodation accommodation
}

class DateRange {
  -Instant start
  -Instant end
}

class Address {
  -Long addressId
  -String address
  -String roadAddress
  -String detailAddress
  -double latitude
  -double longitude
  -String postCode
  -String zone
  +registerAddress(Room)
}

class Review {
  -Member member
  -Room room
  -String title
  -String description
  -double scope
  -Instant createdAt
  +registerReview(Member, Room)
}

class File {
  +uploadFile()
}

class Category {
  -Long categoryId
  -String name
  -String description
  -int sort
  +getCategories()
  +getSubCategories(Category)
}

class SubCategory {
  -Long subCategoryId
  -String name
  -String description
  -int sort
  -int depth
  +getIncludedSubCategoriesOfCategory(Category)
}

enum PaymentMethod {
  REGULAR_CARD
  REGISTER_CARD
}

class Payment {
 +requestPayment(member: Member, accommodation: Accommodation, paymentMethod: PaymentMethod, price: int): void
 +cancelPayment(member: Member, transactionId: String)
}

class RegisterCard {
 +registerCard(member: Member, transactionId: String, pgType: String): void
}

interface PaymentProcess {
 +support(paymentMethod: PaymentMethod): boolean
 +pay(): void
 +cancel(transactionId: String): void
}

class RegularCardPayment implements PaymentProcess {
 +support(paymentMethod: PaymentMethod): boolean
 +pay(): void
 +cancel(transactionId: String): void
}

class RegisterCardPayment implements PaymentProcess  {
 +support(paymentMethod: PaymentMethod): boolean
 +pay(): void
 +cancel(transactionId: String): void
}

class PaymentHistory {
 -Long paymentHistoryId
 -PaymentStatus status
 -Member member
 -String transactionId
 -Long amount
 -String receipt
 -Instant createdAt
}

enum PaymentStatus {
 PAY
 CANCEL
 PARTIAL_CANCEL
}

@enduml