@startuml
class Member {
  -String name
}

class Room {
  +getProvideRoomInfos(): List<Room>
  +reserve(Member, DateRange, Accommodation) : void
}

class Accommodation {
  +getSpecificDateAccommodations(DateRange): List<Accommodation>
  +confirmationReservation(Accommodation) : boolean
}

class Reservation {
  +makeReservation(Member, Accommodation) : boolean
  +getReservationInfos(Member): List<Reservation>
}

class DateRange {
  -Instant start
  -Instant end
}

@enduml